---
engines:
  metric:
    enabled: true
    exclude_paths:
      - "**_test.py"
    config:
      languages:
        - "Python"
  duplication:
    enabled: true
    exclude_paths:
      - "**_test.py"
    config:
      languages:
        - "Python"
