engines:
  duplication:
    exclude_paths:
      - "**_test.py"
    config:
      languages:
        - "Python"
  complexity:
    exclude_paths:
      - "**_test.py"
    config:
      languages:
        - "Python"